-- Barbearia SaaS — schema Supabase
-- Projetos já existentes: rode também database/migrations/20260207_trial_saas.sql (enum trial + funções já podem estar no arquivo abaixo; a migration cobre apenas o que falta).

-- Extensões
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Enums
DO $$ BEGIN
  CREATE TYPE public.profile_role AS ENUM ('barber', 'client');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE public.subscription_status AS ENUM ('trial', 'active', 'expired', 'canceled');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE public.appointment_status AS ENUM ('scheduled', 'canceled');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- Perfis (1:1 com auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  nome TEXT NOT NULL DEFAULT '',
  telefone TEXT NOT NULL DEFAULT '',
  role public.profile_role NOT NULL DEFAULT 'client',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Barbearias (um barbeiro = uma barbearia neste MVP)
CREATE TABLE IF NOT EXISTS public.barbershops (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  nome_barbearia TEXT NOT NULL,
  endereco TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS idx_barbershops_user_id ON public.barbershops (user_id);

-- Assinaturas Stripe
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  status public.subscription_status NOT NULL DEFAULT 'expired',
  stripe_customer_id TEXT,
  stripe_subscription_id TEXT UNIQUE,
  current_period_end TIMESTAMPTZ,
  trial_start_date DATE,
  trial_end_date DATE,
  account_blocked BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON public.subscriptions (user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON public.subscriptions (status);

-- Anti-fraude trial (hashes) e rate limit de cadastro (gravado via service_role / funções)
CREATE TABLE IF NOT EXISTS public.trial_identifier_claims (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4 (),
  kind TEXT NOT NULL CHECK (
    kind = ANY (
      ARRAY['email','phone','device','ip_subnet'::text]
    )
  ),
  value_hash TEXT NOT NULL,
  user_id UUID NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now (),
  UNIQUE (kind, value_hash)
);

CREATE INDEX IF NOT EXISTS idx_trial_claims_user_id ON public.trial_identifier_claims (user_id);

CREATE TABLE IF NOT EXISTS public.signup_rate_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip INET NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now ()
);

CREATE INDEX IF NOT EXISTS idx_signup_rate_ip_time ON public.signup_rate_events (ip, occurred_at DESC);

ALTER TABLE public.trial_identifier_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signup_rate_events ENABLE ROW LEVEL SECURITY;

-- Ofertas de horário por data (inícios explícitos cadastrados pelo barbeiro)
CREATE TABLE IF NOT EXISTS public.agenda_day_slots (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  data DATE NOT NULL,
  hora TIME NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, data, hora)
);

CREATE INDEX IF NOT EXISTS idx_agenda_day_slots_user_data ON public.agenda_day_slots (user_id, data);

-- Serviços oferecidos pelo barbeiro
CREATE TABLE IF NOT EXISTS public.services (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  preco NUMERIC(10, 2) NOT NULL DEFAULT 0,
  duracao_minutos SMALLINT NOT NULL CHECK (duracao_minutos > 0 AND duracao_minutos <= 720),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_services_user_id ON public.services (user_id);

-- Agendamentos (intervalo de tempo + serviço opcional para registros legados)
CREATE TABLE IF NOT EXISTS public.appointments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  barber_id UUID NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  servico_id UUID REFERENCES public.services (id) ON DELETE SET NULL,
  cliente_nome TEXT NOT NULL,
  cliente_telefone TEXT NOT NULL,
  cliente_email TEXT,
  data DATE NOT NULL,
  hora_inicio TIME NOT NULL,
  hora_fim TIME NOT NULL,
  status public.appointment_status NOT NULL DEFAULT 'scheduled',
  access_token UUID NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT appointment_time_order CHECK (hora_fim > hora_inicio),
  CONSTRAINT appointments_access_token_unique UNIQUE (access_token)
);

CREATE INDEX IF NOT EXISTS idx_appointments_barber_date ON public.appointments (barber_id, data);
CREATE INDEX IF NOT EXISTS idx_appointments_barber_date_start
  ON public.appointments (barber_id, data, hora_inicio);

CREATE INDEX IF NOT EXISTS idx_appointments_barber_scheduled_data
  ON public.appointments (barber_id, data)
  WHERE status = 'scheduled';

-- updated_at automático
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_profiles_updated ON public.profiles;
CREATE TRIGGER trg_profiles_updated
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

DROP TRIGGER IF EXISTS trg_barbershops_updated ON public.barbershops;
CREATE TRIGGER trg_barbershops_updated
  BEFORE UPDATE ON public.barbershops
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

DROP TRIGGER IF EXISTS trg_subscriptions_updated ON public.subscriptions;
CREATE TRIGGER trg_subscriptions_updated
  BEFORE UPDATE ON public.subscriptions
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

DROP TRIGGER IF EXISTS trg_services_updated ON public.services;
CREATE TRIGGER trg_services_updated
  BEFORE UPDATE ON public.services
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

DROP TRIGGER IF EXISTS trg_appointments_updated ON public.appointments;
CREATE TRIGGER trg_appointments_updated
  BEFORE UPDATE ON public.appointments
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

-- Perfil na criação do usuário (dados iniciais via raw_user_meta_data no signUp)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  r public.profile_role;
BEGIN
  BEGIN
    r := (NEW.raw_user_meta_data->>'role')::public.profile_role;
  EXCEPTION WHEN OTHERS THEN
    r := 'client';
  END;

  INSERT INTO public.profiles (id, nome, telefone, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'nome', ''),
    COALESCE(NEW.raw_user_meta_data->>'telefone', ''),
    COALESCE(r, 'client')
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

CREATE OR REPLACE FUNCTION public.subscription_grants_public_access (s public.subscriptions)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT
    (s.account_blocked IS NOT TRUE)
    AND (
      (
        s.status = 'active'
        AND (s.current_period_end IS NULL OR s.current_period_end > now ())
      )
      OR (
        s.status = 'trial'
        AND s.trial_end_date IS NOT NULL
        AND s.trial_end_date >= ((now() AT TIME ZONE 'utc'))::date
      )
    );
$$;

CREATE OR REPLACE FUNCTION public.finalize_barber_bootstrap (
  p_user_id uuid,
  p_email_hash text,
  p_phone_hash text,
  p_device_hash text,
  p_ip_subnet_hash text,
  p_nome_barbearia text,
  p_endereco text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_eligible boolean := true;
  v_start date;
  v_end date;
BEGIN
  IF auth.role() = 'authenticated' THEN
    IF auth.uid() IS DISTINCT FROM p_user_id THEN
      RETURN jsonb_build_object('ok', false, 'error', 'unauthorized');
    END IF;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.subscriptions x
    WHERE x.user_id = p_user_id
    LIMIT 1
  ) THEN
    RETURN jsonb_build_object('ok', true, 'already_initialized', true);
  END IF;

  -- Anti-fraude: só e-mail + telefone (hashes fortes). Device/IP compartilhavam
  -- valores iguais (missing / 0.0.0.0/24) e bloqueavam todos após o 1º cadastro.
  IF EXISTS (
      SELECT 1
      FROM public.trial_identifier_claims c
      WHERE (c.kind = 'email' AND c.value_hash = p_email_hash)
         OR (c.kind = 'phone' AND c.value_hash = p_phone_hash)
    LIMIT 1
  ) THEN
    v_eligible := false;
  END IF;

  INSERT INTO public.barbershops (user_id, nome_barbearia, endereco)
  VALUES (
    p_user_id,
    trim(p_nome_barbearia),
    coalesce(nullif(trim(p_endereco), ''), '')
  )
  ON CONFLICT (user_id) DO UPDATE
  SET nome_barbearia = excluded.nome_barbearia,
      endereco = excluded.endereco,
      updated_at = now ();

  IF v_eligible THEN
    v_start := ((now() AT TIME ZONE 'utc'))::date;
    v_end := v_start + 13;

    INSERT INTO public.subscriptions (
      user_id,
      status,
      trial_start_date,
      trial_end_date,
      account_blocked,
      stripe_customer_id,
      stripe_subscription_id,
      current_period_end
    )
    VALUES (
      p_user_id,
      'trial',
      v_start,
      v_end,
      false,
      NULL,
      NULL,
      NULL
    );

    INSERT INTO public.trial_identifier_claims (kind, value_hash, user_id)
    VALUES
      ('email', p_email_hash, p_user_id),
      ('phone', p_phone_hash, p_user_id);
  ELSE
    INSERT INTO public.subscriptions (
      user_id,
      status,
      trial_start_date,
      trial_end_date,
      account_blocked,
      stripe_customer_id,
      stripe_subscription_id,
      current_period_end
    )
    VALUES (
      p_user_id,
      'expired',
      NULL,
      NULL,
      true,
      NULL,
      NULL,
      NULL
    );
  END IF;

  RETURN jsonb_build_object(
    'ok',
    true,
    'trial_eligible',
    v_eligible,
    'trial_started',
    v_eligible,
    'account_blocked_after',
    NOT v_eligible
  );
END;
$$;

REVOKE ALL ON FUNCTION public.finalize_barber_bootstrap (
  uuid, text, text, text, text, text, text
) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.finalize_barber_bootstrap (
  uuid, text, text, text, text, text, text
) TO service_role;

GRANT EXECUTE ON FUNCTION public.finalize_barber_bootstrap (
  uuid, text, text, text, text, text, text
) TO authenticated;

REVOKE ALL ON FUNCTION public.subscription_grants_public_access (public.subscriptions) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.subscription_grants_public_access (public.subscriptions) TO anon, authenticated;

-- RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.barbershops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agenda_day_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

-- profiles
DROP POLICY IF EXISTS "profiles_select_own" ON public.profiles;
CREATE POLICY "profiles_select_own"
  ON public.profiles FOR SELECT
  TO authenticated
  USING (id = auth.uid());

DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own"
  ON public.profiles FOR UPDATE
  TO authenticated
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

-- barbershops: leitura pública só com assinatura ativa; dono sempre vê a sua
DROP POLICY IF EXISTS "barbershops_select_public" ON public.barbershops;
CREATE POLICY "barbershops_select_public"
  ON public.barbershops FOR SELECT
  TO anon, authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.subscriptions s
      WHERE s.user_id = barbershops.user_id
        AND public.subscription_grants_public_access (s)
    )
  );

DROP POLICY IF EXISTS "barbershops_select_owner" ON public.barbershops;
CREATE POLICY "barbershops_select_owner"
  ON public.barbershops FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "barbershops_insert_owner" ON public.barbershops;
CREATE POLICY "barbershops_insert_owner"
  ON public.barbershops FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "barbershops_update_owner" ON public.barbershops;
CREATE POLICY "barbershops_update_owner"
  ON public.barbershops FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "barbershops_delete_owner" ON public.barbershops;
CREATE POLICY "barbershops_delete_owner"
  ON public.barbershops FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());

-- subscriptions: leitura do próprio usuário; escrita apenas service_role (sem policies para authenticated)
DROP POLICY IF EXISTS "subscriptions_select_own" ON public.subscriptions;
CREATE POLICY "subscriptions_select_own"
  ON public.subscriptions FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

-- subscriptions: leitura pública APENAS para linhas ativas
-- Necessário porque outras policies (barbershops/services/agenda_day_slots) usam EXISTS(subscriptions)
-- e o RLS de subscriptions bloqueia o subselect para anon se não houver policy de SELECT.
DROP POLICY IF EXISTS "subscriptions_select_public_active" ON public.subscriptions;
CREATE POLICY "subscriptions_select_public_active"
  ON public.subscriptions FOR SELECT
  TO anon, authenticated
  USING (public.subscription_grants_public_access (subscriptions));

-- agenda_day_slots: dono sempre lê; público só barbeiros com assinatura ativa
DROP POLICY IF EXISTS "agenda_day_slots_select_own" ON public.agenda_day_slots;
CREATE POLICY "agenda_day_slots_select_own"
  ON public.agenda_day_slots FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "agenda_day_slots_select_public_active" ON public.agenda_day_slots;
CREATE POLICY "agenda_day_slots_select_public_active"
  ON public.agenda_day_slots FOR SELECT
  TO anon, authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.subscriptions s
      WHERE s.user_id = agenda_day_slots.user_id
        AND public.subscription_grants_public_access (s)
    )
  );

DROP POLICY IF EXISTS "agenda_day_slots_insert_own" ON public.agenda_day_slots;
CREATE POLICY "agenda_day_slots_insert_own"
  ON public.agenda_day_slots FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "agenda_day_slots_update_own" ON public.agenda_day_slots;
CREATE POLICY "agenda_day_slots_update_own"
  ON public.agenda_day_slots FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "agenda_day_slots_delete_own" ON public.agenda_day_slots;
CREATE POLICY "agenda_day_slots_delete_own"
  ON public.agenda_day_slots FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());

-- services: dono; leitura pública com assinatura ativa (página do cliente)
DROP POLICY IF EXISTS "services_select_own" ON public.services;
CREATE POLICY "services_select_own"
  ON public.services FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "services_select_public_active" ON public.services;
CREATE POLICY "services_select_public_active"
  ON public.services FOR SELECT
  TO anon, authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.subscriptions s
      WHERE s.user_id = services.user_id
        AND public.subscription_grants_public_access (s)
    )
  );

DROP POLICY IF EXISTS "services_insert_own" ON public.services;
CREATE POLICY "services_insert_own"
  ON public.services FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "services_update_own" ON public.services;
CREATE POLICY "services_update_own"
  ON public.services FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "services_delete_own" ON public.services;
CREATE POLICY "services_delete_own"
  ON public.services FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());

-- appointments: barbeiro vê e atualiza os seus; insert público NÃO — use Server Action + service role
DROP POLICY IF EXISTS "appointments_select_barber" ON public.appointments;
CREATE POLICY "appointments_select_barber"
  ON public.appointments FOR SELECT
  TO authenticated
  USING (barber_id = auth.uid());

DROP POLICY IF EXISTS "appointments_update_barber" ON public.appointments;
CREATE POLICY "appointments_update_barber"
  ON public.appointments FOR UPDATE
  TO authenticated
  USING (barber_id = auth.uid())
  WITH CHECK (barber_id = auth.uid());

-- Agendamentos: sem SELECT público direto em `appointments` — link por token via RPC `get_appointment_public_by_access_token`.
-- Índice implícito: constraint UNIQUE(access_token) na tabela.

CREATE OR REPLACE FUNCTION public.get_appointment_public_by_access_token (p_token uuid)
RETURNS TABLE (
  data date,
  hora_inicio time,
  hora_fim time,
  cliente_nome text,
  cliente_telefone text,
  cliente_email text,
  status public.appointment_status,
  nome_barbearia text,
  nome_servico text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    a.data,
    a.hora_inicio,
    a.hora_fim,
    a.cliente_nome,
    a.cliente_telefone,
    a.cliente_email,
    a.status,
    b.nome_barbearia,
    s.nome AS nome_servico
  FROM public.appointments a
  INNER JOIN public.barbershops b ON b.user_id = a.barber_id
  LEFT JOIN public.services s ON s.id = a.servico_id
  WHERE a.access_token = p_token
  LIMIT 1;
$$;

REVOKE ALL ON FUNCTION public.get_appointment_public_by_access_token (uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_appointment_public_by_access_token (uuid) TO anon, authenticated;
