-- Segurança: remove SELECT público em subscriptions (vazava stripe_* via anon key).
-- Substitui subselects em policies por função SECURITY DEFINER.
-- Rate limit de agendamento público + RPC de token sem PII completa.

-- 1) Checagem pública sem expor linhas de subscriptions
CREATE OR REPLACE FUNCTION public.barber_has_public_access (p_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.subscriptions s
    WHERE s.user_id = p_user_id
      AND public.subscription_grants_public_access (s)
  );
$$;

REVOKE ALL ON FUNCTION public.barber_has_public_access (uuid) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.barber_has_public_access (uuid) TO anon,
authenticated;

-- 2) Policies que liam subscriptions diretamente
DROP POLICY IF EXISTS "subscriptions_select_public_active" ON public.subscriptions;

DROP POLICY IF EXISTS "barbershops_select_public" ON public.barbershops;

CREATE POLICY "barbershops_select_public" ON public.barbershops FOR SELECT TO anon,
authenticated
USING (public.barber_has_public_access (user_id));

DROP POLICY IF EXISTS "services_select_public_active" ON public.services;

CREATE POLICY "services_select_public_active" ON public.services FOR SELECT TO anon,
authenticated
USING (public.barber_has_public_access (user_id));

DROP POLICY IF EXISTS "agenda_day_slots_select_public_active" ON public.agenda_day_slots;

CREATE POLICY "agenda_day_slots_select_public_active" ON public.agenda_day_slots FOR SELECT TO anon,
authenticated
USING (public.barber_has_public_access (user_id));

-- 3) Rate limit agendamento público (service_role only; sem policies)
CREATE TABLE IF NOT EXISTS public.booking_rate_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip INET NOT NULL,
  barbershop_id UUID NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now ()
);

CREATE INDEX IF NOT EXISTS idx_booking_rate_ip_shop_time ON public.booking_rate_events (ip, barbershop_id, occurred_at DESC);

ALTER TABLE public.booking_rate_events ENABLE ROW LEVEL SECURITY;

-- 4) RPC público: sem telefone/e-mail completos
DROP FUNCTION IF EXISTS public.get_appointment_public_by_access_token (uuid);

CREATE FUNCTION public.get_appointment_public_by_access_token (p_token uuid)
RETURNS TABLE (
  data date,
  hora_inicio time,
  hora_fim time,
  cliente_nome text,
  status public.appointment_status,
  nome_barbearia text,
  nome_servico text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    a.data,
    a.hora_inicio,
    a.hora_fim,
    a.cliente_nome,
    a.status,
    b.nome_barbearia,
    s.nome AS nome_servico
  FROM public.appointments a
  INNER JOIN public.barbershops b ON b.user_id = a.barber_id
  LEFT JOIN public.services s ON s.id = a.servico_id
  WHERE a.access_token = p_token
  LIMIT 1;
$$;

REVOKE ALL ON FUNCTION public.get_appointment_public_by_access_token (uuid) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.get_appointment_public_by_access_token (uuid) TO anon,
authenticated;
