-- Trial de 14 dias, bloqueio, anti-fraude (identificadores) e políticas públicas.
-- Aplicar no SQL Editor do Supabase ou via CLI (revisão recomendada em produção).
--
-- ORDEM OBRIGATÓRIA NO SUPABASE:
--   PASSO A) Rode apenas: database/migrations/20260207_trial_saas_step1_enum_only.sql
--   PASSO 0) Erro "relation ... services"? Rode antes:
--            database/migrations/20260207_before_step2_missing_core_tables.sql
--   PASSO B) Rode o restante DESTE arquivo (colunas trial, funções, policies públicas).
-- Colunas em subscriptions
ALTER TABLE public.subscriptions
  ADD COLUMN IF NOT EXISTS trial_start_date date,
  ADD COLUMN IF NOT EXISTS trial_end_date date,
  ADD COLUMN IF NOT EXISTS account_blocked boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.subscriptions.account_blocked IS
  'true = conta bloqueada (trial expirado, pagamento falhou, cancelamento Stripe, etc.).';

-- 2) CPF normalizado apenas dígitos no perfil
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS cpf text NOT NULL DEFAULT '';

-- 3) Identificadores de trial (somente hashes; SEM dados em claro).
CREATE TABLE IF NOT EXISTS public.trial_identifier_claims (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4 (),
  kind text NOT NULL CHECK (
    kind = ANY (
      ARRAY['email','cpf','phone','device','ip_subnet'::text]
    )
  ),
  value_hash text NOT NULL,
  user_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now (),
  UNIQUE (kind, value_hash)
);

CREATE INDEX IF NOT EXISTS idx_trial_claims_user_id ON public.trial_identifier_claims (user_id);

-- 4) Rate limit bruteforce cadastro por IP (gravado via service_role)
CREATE TABLE IF NOT EXISTS public.signup_rate_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip inet NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT now ()
);

CREATE INDEX IF NOT EXISTS idx_signup_rate_ip_time ON public.signup_rate_events (ip, occurred_at DESC);

ALTER TABLE public.trial_identifier_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signup_rate_events ENABLE ROW LEVEL SECURITY;

-- Sem policies: anon/authenticated não leem estas tabelas via PostgREST (service_role ignora RLS).

-- 5) Função predicado nas policies públicas (ativo + trial UTC)
CREATE OR REPLACE FUNCTION public.subscription_grants_public_access (s public.subscriptions)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT
    (s.account_blocked IS NOT TRUE)
    AND (
      (
        s.status = 'active'
        AND (s.current_period_end IS NULL OR s.current_period_end > now ())
      )
      OR (
        s.status = 'trial'
        AND s.trial_end_date IS NOT NULL
        AND s.trial_end_date >= ((now() AT TIME ZONE 'utc'))::date
      )
    );
$$;

-- 6) Função finalize_barber_bootstrap (service_role apenas)
CREATE OR REPLACE FUNCTION public.finalize_barber_bootstrap (
  p_user_id uuid,
  p_email_hash text,
  p_cpf_hash text,
  p_phone_hash text,
  p_device_hash text,
  p_ip_subnet_hash text,
  p_nome_barbearia text,
  p_endereco text,
  p_cpf_digits text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_eligible boolean := true;
  v_start date;
  v_end date;
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.subscriptions x
    WHERE x.user_id = p_user_id
    LIMIT 1
  ) THEN
    RETURN jsonb_build_object('ok', true, 'already_initialized', true);
  END IF;

  IF EXISTS (
      SELECT 1
      FROM public.trial_identifier_claims c
      WHERE (c.kind = 'email' AND c.value_hash = p_email_hash)
         OR (c.kind = 'cpf' AND c.value_hash = p_cpf_hash)
         OR (c.kind = 'phone' AND c.value_hash = p_phone_hash)
         OR (c.kind = 'device' AND c.value_hash = p_device_hash)
         OR (c.kind = 'ip_subnet' AND c.value_hash = p_ip_subnet_hash)
    LIMIT 1
  ) THEN
    v_eligible := false;
  END IF;

  INSERT INTO public.barbershops (user_id, nome_barbearia, endereco)
  VALUES (
    p_user_id,
    trim(p_nome_barbearia),
    coalesce(nullif(trim(p_endereco), ''), '')
  )
  ON CONFLICT (user_id) DO UPDATE
  SET nome_barbearia = excluded.nome_barbearia,
      endereco = excluded.endereco,
      updated_at = now ();

  UPDATE public.profiles
  SET cpf = coalesce(nullif(trim(p_cpf_digits), ''), cpf)
  WHERE id = p_user_id;

  IF v_eligible THEN
    v_start := ((now() AT TIME ZONE 'utc'))::date;
    v_end := v_start + 13;

    INSERT INTO public.subscriptions (
      user_id,
      status,
      trial_start_date,
      trial_end_date,
      account_blocked,
      stripe_customer_id,
      stripe_subscription_id,
      current_period_end
    )
    VALUES (
      p_user_id,
      'trial',
      v_start,
      v_end,
      false,
      NULL,
      NULL,
      NULL
    );

    INSERT INTO public.trial_identifier_claims (kind, value_hash, user_id)
    VALUES
      ('email', p_email_hash, p_user_id),
      ('cpf', p_cpf_hash, p_user_id),
      ('phone', p_phone_hash, p_user_id),
      ('device', p_device_hash, p_user_id),
      ('ip_subnet', p_ip_subnet_hash, p_user_id);
  ELSE
    INSERT INTO public.subscriptions (
      user_id,
      status,
      trial_start_date,
      trial_end_date,
      account_blocked,
      stripe_customer_id,
      stripe_subscription_id,
      current_period_end
    )
    VALUES (
      p_user_id,
      'expired',
      NULL,
      NULL,
      true,
      NULL,
      NULL,
      NULL
    );
  END IF;

  RETURN jsonb_build_object(
    'ok',
    true,
    'trial_eligible',
    v_eligible,
    'trial_started',
    v_eligible,
    'account_blocked_after',
    NOT v_eligible
  );
END;
$$;

REVOKE ALL ON FUNCTION public.finalize_barber_bootstrap (
  uuid, text, text, text, text, text, text, text, text
) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.finalize_barber_bootstrap (
  uuid, text, text, text, text, text, text, text, text
) TO service_role;

REVOKE ALL ON FUNCTION public.subscription_grants_public_access (public.subscriptions) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.subscription_grants_public_access (public.subscriptions) TO anon, authenticated;

-- 7) Policies RLS públicas
DROP POLICY IF EXISTS "barbershops_select_public" ON public.barbershops;

CREATE POLICY "barbershops_select_public"
  ON public.barbershops FOR SELECT
  TO anon, authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.subscriptions s
      WHERE s.user_id = barbershops.user_id
        AND public.subscription_grants_public_access (s)
    )
  );

DROP POLICY IF EXISTS "availability_select_public_active" ON public.availability;

CREATE POLICY "availability_select_public_active"
  ON public.availability FOR SELECT
  TO anon, authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.subscriptions s
      WHERE s.user_id = availability.user_id
        AND public.subscription_grants_public_access (s)
    )
  );

DROP POLICY IF EXISTS "services_select_public_active" ON public.services;

CREATE POLICY "services_select_public_active"
  ON public.services FOR SELECT
  TO anon, authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.subscriptions s
      WHERE s.user_id = services.user_id
        AND public.subscription_grants_public_access (s)
    )
  );

DROP POLICY IF EXISTS "subscriptions_select_public_active" ON public.subscriptions;

CREATE POLICY "subscriptions_select_public_active"
  ON public.subscriptions FOR SELECT
  TO anon, authenticated
  USING (public.subscription_grants_public_access (subscriptions));

